### ISSUE TITLE
[REQ] FFmpeg v7.1 builds

### ISSUE THREAD

**Issue by Barough** [defisym/FFmpeg-Builds-Win32#2]
Any chance of getting FFmpeg v7.1 builds?

**Comment by defisym** [comment]
[An issue](https://trac.ffmpeg.org/ticket/10833) fixed in 7.x is not back ported to 6.1, which causes build failure in 6.x variants with latest script (which updated mingw version) and prevents the release. 
Posted this issue to [FFMpeg tracker](https://trac.ffmpeg.org/ticket/11234) but IDK how long it will take to get it fixed.
